language: python
script:
- python -m pytest -v
notifications:
  slack:
    secure: QJ1T/5AFOYDfYd3PwBHKgBmUqBTBLEk8oZKMDqXCYfSDT6cckGv5JTTdhjHbxbxLzegVZgjmbIsmsIwDVPrV/gU1pplD/rHktF5l66PL/AsJ4nkxE3EpuGCduav8LF/6G3BcjxjfHcxORRYrFX7is0CEyeVFSuEv2FtMl351RL9+GFDBtnWXgaQ+lh5QVg9+uAHSI0ogJfXADN3Hs5wMYGut0Qwb0fK/5PehYRto23LuprlQ9exIoh7BNh4eiMrQmkvSmY0l4YdWtkOGnDSU7TxXyggrZv8l4b2TKjNYYel3b/jT3IFF258ho0+5uLBYdJ1VeYpkvhkWlPq54gBWXHun1qvpITaCcnVU7DExQXtAFDTatjdtChNJLr5SPDePJ7Z4Y5QXZRpJ32aOH+SXsDELs7BkNOMvzBNI5T7VnrMO/rmp2GuK5+AJXlPTQ0pmyZTQ4FZSoqpz5CJNerkRKYBcpogRKu4OQq1q59NaxUofEJG/s/Gx3kHOjUz0g0FbErjN2w4Df7wp7IkXno6yPdg22oUaasrfbWOLLjRpdR2LGxdlIJ/LRyKMXSMqaH1RXdR05LITvapiIXyAxbNyQR02hEChFTr1iXOiADZcFHrezKAqxSjABmWgMGMrMNAgllxLqfLjvdX3+D6b0KmjjqZIHJg6VNUvKYAlsFL/3x4=
