language: ruby
rvm:
- 2.2
- jruby
notifications:
  slack:
    secure: oje+/aOoTK+TFMNJP93cF2HJfViab7X33DOojTWFqk6ZVX2EpBItQplVPO56JN627+txQ9CVVZGxZJI6sxYE9KRTKzc01rgXRFJlm7NxjHdqnO8+lEI4/oZe+GYpn3oxLiqSPqY9U2t5r+vZED48smPxOv3PxaLZ0EUm0o4jSU9ix9imPqSyPjPot+gayDeLVdzDxp5nSdoIH/vXp1szVgzba/v7hzEPTGMpwBJiCwoEEOh5/4mPKYbp4KdmjFOeFTM6teKvtu0TNmN0hcT0Yr6UhTtyfLkXJVuXgEkkQdyIanuedXxbgppTkA05uhHNmiDy3rvePaF/by3Xlha97V/01EjwE/EYPjiYaCn1EkBJAaDt/jIFf6YMRVyefZQifGTgVy4OyNouh4UPW265zokQlNxgN/crKWFOd0fs8FJmb3E+0n/xASA455Sp5QQ00YekNpOK0DWKDy0jbgCjiFtn6tzWcKs+MKbVpp6ua3M4jv5gyBdm4gaQlUPmNWk41MWdB9gmtp+nqsYGN+XO38M+NPnK7Qiuprd9rdfQThd6AaRDMjWsDTL/fZF7ADzrZhMJ3CJTie1nwIB25gXe6LWk3uGwqY0DaARr0M2ZQa3ipCv7I6/4PQEQ0qi2+ZlYyKbESGnALnz8wgxeCbn+l8cNosBavEpNLXGokU8WMKo=
